cgroup:
  root: /sys/fs/cgroup
  name: processmaster
  memory_max: MAX
  memory_swap_max: MAX
  cpu_max: MAX

unix_socket:
  path: /tmp/processmaster-example.sock
  owner: null
  group: null
  mode: 660

global:
  config_directory: ./config.d

  # If you want processmaster itself to drop privileges (when started as root), set:
  # user: someuser
  # group: somegroup
